config/routes.rb
Rails.application.routes.draw do
  #resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #get "recipes" => "recipes#index"
  root 'recipes#index'
  resources :recipes do 
    resources :comments
  end

end

#commands 

#Migration (atenção, seguir as convenções, nome da migrate singular em ingles)
#rails g migration {Name} field field_text:text number:integer amount:decimal
#rails g migration AddNewFieldsTo{Name} bigtext:text field_two fields:integer

#Migration + Models + Controller + Routes com relacionamento 1xn
#Resource de commendarios para a tabela de Receitas
#rails g resource comment name:string rate:integer comment:text recipe:reference

#Exec migratinos
#rake db:migrate
#rake db:rollback #desfaz a ultima migração
#rake db:seed
#rake db:reset #limpa,cria mas migracoes e roda seed

#Controller
#rails g controller {Name}

#Rodar o server em outra porta
#rails s -p 4000

#Ao mexer no GEMGILE rodar o bundle
#bundle instal --without production

#Ao add novos assets tem q reestartar a aplicação

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :name, :rating, :comment, presence:true
    validates_length_of :comment, maximum:400

    RATING=[0,1,2,3,4,5]
    validates_inclusion_of :rating, in:RATING


    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, :stuff, :duration, :prepare_mode, presence:true
    validates_length_of :stuff, maximum: 400
    validates_length_of :prepare_mode, maximum: 400
    validates_numericality_of :calories, greather_than_or_equals_to:0, presence:true
    validates_format_of :poster, allow_blank: true, with: /\w+\.(gif|jpg|png|webp)\z/i, message: " utilizar somente arquivos GIF, JPEG ou PNG"
    
    KIND = %w(Carnes Aves Peixes Massas Saladas Doces)
    validates_inclusion_of :kind, in:KIND

    has_many :comments , dependent: :destroy

    def light?
        calories < 130
    end

    def self.created_at 
        where('created_at <= ?', Time.now).order('created_at DESC')
    end

    # formas de fazer consultas no bd
    # Recipe.all
    # Recipe.count
    # Recipe.order('nome_do_campo DESC')
    # Recipe.find(1)
    # Recipe.find_by(name: 'teste')
    # Recipe.where('campo <= ?', valor)
    # Recipe.where('created_at <= ?', Time.now).order('created_at DESC')

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :set_recipe

    def index
        
        @comments = @recipe.comments
    end

    def new
        
        @comment = @recipe.comments.new
    end

    def create
        
        @comment = @recipe.comments.new(comment_params)
        if @comment.save 
            redirect_to recipe_comments_path(@recipe), notice: 'Comentario gravado com sucesso'
        else
            render :new
        end
    end


    private 
        def comment_params
            #comment_params = params.require(:recipe).permit!
            params.require(:comment).permit(:name, :rating, :comment)
        end

        def set_recipe
            @recipe = Recipe.find(params[:recipe_id])
        end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.created_at
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe, notice:"Receita atualizada com sucesso"
        else
            render :edit
        end
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to @recipe, notice:"Receita criada com sucesso"
        else
            render :new
        end
    end

    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy

        redirect_to recipes_url , alert:"Receita apagada com sucesso"
    end

    private 
        def recipe_params
            #recipe_params = params.require(:recipe).permit!
            recipe_params = params.require(:recipe).permit(:name,:stuff,:calories,:prepare_mode,:cost,:kind,:portion,:duration,:poster)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

    def formata_caloria(recipe)
        if recipe.light?
            content_tag(:strong, "Light (menos de 130 calorias)")
        else
            recipe.calories
        end
    end

    def imagem(recipe, size)
        if recipe.poster.blank?
            "sem imagem"
        else
            image_tag(recipe.poster, size: size)
        end

    end
end

app/views/comments/_form.html.erb
<%= form_for( [@recipe, @comment] ) do |f|  %>

<%= render 'layouts/errors', object: @comment  %>

<div class="form-group">
    <%= f.label :Nome %>:
    <%= f.text_field :name , class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Estrelas %>:
    <%= f.select :rating, Comment::RATING, prompt:'Escolha a quantidade de estrelas', class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Comentário %>:
    <%= f.text_area :comment, cols:20, rows:5 , class:"form-control"  %>
</div>

<div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancalar", root_path, class: 'btn btn-default'  %>
</div>

<% end %>

app/views/comments/index.html.erb
<div class="container">
    <% if @recipe.comments.size > 0 %>
    <div class="jumbotron">
        <ul>
            <% @comments.each do |comment| %>
            <li>
                <p> <%= comment.name %> <small class="small_font_rating"> <%= pluralize(comment.rating, 'estrla', 'estrelas') %> </small>
                    <small class="small_font"> - <%= time_ago_in_words(comment.created_at) %> atrás </small> </p>
                <p><%= comment.comment %></p>
            <li>
            <% end %>
        </ul>
    </div>
    <% else %>
    <div class="alert alert-warning">
        <p>Não foi encontrado nenhum comentário</p>
    </div>
    <% end %>


    <%= link_to recipes_path, class:'btn btn-link' do %>
        <i class="glyphicon glyphicon-home"> Receitas </i>
    <% end %>

</div>

app/views/comments/new.html.erb
<div class="container">

    <div class="panel panel-default">
        <div class="panel-heading">Novo Comentário</div>
        <div class="panel-body">
            <%= render partial: "form" %>
        </div>
    </div>

</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        <ul>
            <% object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        <ul>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class="container"> 
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= flash[:notice] %>
        </div>
    </div>
    <% elsif flash[:alert] %>
    <div class="container"> 
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= flash[:alert] %>
        </div>
    </div>
    <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <p class="text-muted"> Receitas fácil com RADreceitas.</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("logo.png", size:'30', alt:'webreceita'), root_path, class:'navbar-brand' %>
            <%= link_to "RADreceitas", root_path, class:'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        
        
            <ul class="nav navbar-nav navbar-right">
                <li> <%= link_to "Receitas", root_path %> </li>
                
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RADreceitas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>

   <%= render "layouts/flash" %>

    <%= yield %>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for( @recipe ) do |f|  %>

<%= render 'layouts/errors', object: @recipe  %>

<div class="form-group">
    <%= f.label :Nome %>:
    <%= f.text_field :name , class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Ingredientes %>:
    <%= f.text_area :stuff, cols:20, rows:5 , class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Tipo %>:
    <%= f.select :kind, Recipe::KIND, prompt:'Escolha uma opção', class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Calorias %>:
    <%= f.number_field :calories , class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Mode_de_preparo %>:
    <%= f.text_area :prepare_mode, cols:20, rows:5 , class:"form-control"  %>
</div>

<div class="form-group">
    <%= f.label :Tempo_de_Preparo %>:
    <%= f.time_select :duration , class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Porções %>:
    <%= f.text_field :portion , class:"form-control" %>
</div>

<div class="form-group">
    <%= f.label :Custo %>:
    <%= f.number_field :cost , class:"form-control"  %>
</div>

<div class="form-group">
    <%= f.label :Poster %>:
    <%= f.text_field :poster , class:"form-control"  %>
    <%
=begin%>
 <%= f.file_field :poster, placeholder: ".GIF, .JPEG ou .PNG" %> 
<%
=end%>
</div>

<div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancalar", root_path, class: 'btn btn-default'  %>
</div>



<% end %>

app/views/recipes/edit.html.erb
<div class="container">

    <div class="panel panel-default">
        <div class="panel-heading">Editando Receita</div>
        <div class="panel-body">
            <%= render partial: "form" %>
        </div>
    </div>

</div>

app/views/recipes/index.html.erb
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"> 
                <%= pluralize(@recipes.size, 'Receita', 'Receitas') %> 
                <small class="nova_receita">
                    <%= link_to "Nova Receita", new_recipe_path %>
                </small>
            </h1>
        </div>
    </div>

    <% @recipes.each do |recipe| %>
        <div class="row">
            <div class="col-md-2">
                <%= link_to imagem(recipe, 150), recipe %>
            </div>

            <div class="col-md-7">
                <h3><%= link_to recipe.name, recipe %></h3>
                <p><%= truncate(recipe.stuff, length:30, separator: ' ') %></p>

                <h4>Calorias</h4>
                <p>
                    <%= formata_caloria(recipe) %>
                </p>

                <h4>Tempo de Preparo</h4>
                <p>
                    <%= recipe.duration %> min
                </p>


                <h4>Custo</h4>
                <p>
                    <%= number_to_currency(recipe.cost) %>
                </p>
            </div>
        </div>
    <%end %>

</div>

app/views/recipes/new.html.erb
<div class="container">

    <div class="panel panel-default">
        <div class="panel-heading">Nova Receita</div>
        <div class="panel-body">
            <%= render partial: "form" %>
        </div>
    </div>

</div>

app/views/recipes/show.html.erb
<div class="container">
    <div class="jumbotron">

        <p> <%= @message %> </p>

        <article>
            <header>
                <h2><%= @recipe.name %></h2>
                <%= imagem(@recipe, 150) %>
            </header>

            <p>
            <%=  @recipe.kind %>
            </p>
            <p>
            <%=  @recipe.stuff %>
            </p>
            <p>
                <%= formata_caloria(@recipe) %>
            </p>
            <p>
                <%= @recipe.prepare_mode %>
            </p>
            <p>
            <%=  @recipe.duration %>
            </p>
            <p>
                <%= pluralize(@recipe.portion,'Porção',' Porções') %>
            </p>
            <p>
            <%=  @recipe.stuff %>
            </p>
            <p>
                <%= number_to_currency(@recipe.cost) %>
            </p>
        </article>
                
        <%= link_to recipes_path, class:'btn btn-link' do %>
            <i class="glyphicon glyphicon-home"> Receitas </i>
        <% end %>

        <%= link_to edit_recipe_path(@recipe) , class:'btn btn-link' do %>
            <i class="glyphicon glyphicon-edit"> Editar </i>
        <% end %>

        <%= link_to recipe_path(@recipe), method: :delete, data: { confirm: "Deseja deletar esta receita?" } , class:'btn btn-link' do %>
            <i class="glyphicon glyphicon-remove-sign"> Excluir </i>
        <% end %>

        <hr />

        <%= link_to new_recipe_comment_path(@recipe), class:'btn btn-link' do %>
            <i class="glyphicon glyphicon-plus"> Add Comentário </i>
        <% end %>

        <%= link_to recipe_comments_path(@recipe), class:'btn btn-link' do %>
            <i class="glyphicon glyphicon-eye-open"> <%= pluralize(@recipe.comments.size, 'Comentário', 'Comentários') %> </i>
        <% end %>

    </div>
    </div>